Initial project management
htw-exam-planner/exam-planner-documentation pull request #12
Opened 2018-06-18 15:20 UTC by DevWurm

2018-06-20 07:33 UTC, revilovs requested changes

2018-06-20 07:33 UTC, revilovs commented on Project Management/documentation.md
> +- Grundlegende Fehler in den einzelnen Stufen sind aufgrund der kleinen Projekt- und Problemgröße ausreichen unwahrscheinlich, kleine Fehler können durch das Konzept der Rückkopplung korrigiert werde
Typo: ausreichen**d**

2018-06-20 07:33 UTC, revilovs commented on Project Management/documentation.md
> +- Grundlegende Fehler in den einzelnen Stufen sind aufgrund der kleinen Projekt- und Problemgröße ausreichen unwahrscheinlich, kleine Fehler können durch das Konzept der Rückkopplung korrigiert werde
Punkt am Ende der Sätze (gilt für alle obigen)

2018-06-20 07:33 UTC, revilovs commented on Project Management/documentation.md
> +![Wasserfallmodell mit Rückkopplung](https://media.githubusercontent.com/media/htw-exam-planner/exam-planner-documentation/a84f2c8351b1ebc3d4f3a07be578402ee540f0be/images/wasserwrueck.jpg)
Hier den Pfad innerhalb des Projektes, oder?

2018-06-20 07:33 UTC, revilovs commented on Project Management/documentation.md
> +| M3 | Der Softwareentwurf ist abgeschlossen | 18. Juni 2018 |
Sollte man vllt. sagen "der vorläufige Entwurf", da bei Wasserfall mit Rückkopplung ja auch im Nachhinein noch rumgebastelt wird?

2018-06-28 09:57 UTC, revilovs requested changes
Siehe voriger Review

2018-07-15 13:12 UTC, revilovs submitted a review, later dismissed

2018-07-15 19:38 UTC, revilovs submitted a review, later dismissed

2018-07-15 20:07 UTC, revilovs approved these changes

2018-07-15 20:08 UTC, DevWurm reviewed
👍

2018-07-15 20:12 UTC, merged