Aktualisierung des Entwurfes
htw-exam-planner/exam-planner-documentation pull request #17
Opened 2018-07-09 17:48 UTC by denisk176

Ich habe das Klassendiagramm des Repos mal auf den aktuellen Stand gebracht und die PNGs neu exportiert

2018-07-09 17:59 UTC, revilovs requested changes
Nur ein paar Kleinigkeiten:
- Das Paket Repository ist nicht mehr sichtbar im Diagramm
- Die Notiz, dass nicht alle Getter und Setter dargestellt sind, muss weg
- Wenn du noch Zeit hast, wäre es super wenn du DBRepositrory gleich auch noch updatest auf den aktuellen stand
- Die Sichtbarkeiten der Member (`public` und `private`, im Diagramm sichtbar als `+` und `-`)

2018-07-09 18:26 UTC, denisk176 commented
DBRepositrory aktualisiere mache ich gleich noch

2018-07-09 19:35 UTC, revilovs requested changes
- Könntest du das Paket Repository bitte wieder auf die gleich Breite wie Models bringen? Sieht einfach ordentlicher aus
- Visibility von connection ist `private`
- Bei instance das `=null` bitte weg
- Ansonsten super

2018-07-10 07:21 UTC, revilovs requested changes
- Das Paket Repo ist zu weit vorne, sodass man die Enden der Assoziationslinien nicht sieht
- `Reservation.getGroup` ist nicht static und es fehlt der Returntyp

2018-07-10 18:06 UTC, revilovs approved these changes

2018-07-11 04:38 UTC, DevWurm approved these changes

2018-07-11 08:44 UTC, merged