Added Mitschrift Meilensteintreffen
htw-exam-planner/exam-planner-documentation pull request #2
Opened 2018-05-16 16:57 UTC by denisk176

Hallo Leute,

anbei wie von Leo gewünscht, mein Teil der Mitschrift zum 2. Meilensteintreffen. Da ich eher gehen musste, ist hier mein Teil, den ich mir aufgeschrieben habe.

2018-05-16 17:01 UTC, DevWurm requested changes
Noch ein paar Notizen über den Ablauf des Termins (Anwesende, Themen, Inhalte) wären noch gut. Aber die Todos sind schonmal hilfreich. Vielleicht kannst du dich mit @fbkr absprechen

2018-05-16 21:24 UTC, revilovs requested changes
Gute Idee, @fbkr ergänze bitte einfach deine Mitschrift auf diesem Branch, dann ist das gleich beieinander

2018-05-29 22:31 UTC, DevWurm commented
@denisk176 ist alles aus diesem Branch in #6 enthalten? Dann können wir den hier schließen

2018-06-04 14:33 UTC, denisk176 commented
Ja, da ist alles aus dem Branch drin. Ich merge den mal.

2018-06-04 14:33 UTC, closed without merging