Entwurfsdoku 2
htw-exam-planner/exam-planner-documentation pull request #22
Opened 2018-07-15 19:35 UTC by revilovs

Die aktualisierte Entwurfsdoku mit MVP

2018-07-15 20:06 UTC, DevWurm requested changes

2018-07-15 20:06 UTC, DevWurm commented on Entwurf/entwurfsdoku.tex
> +Der Grobentwurf (dargestellt in Abbildung \ref{fig:Paketdiagramm_Grobentwurf}) wurde nach der 3-Schichtenarchitektur aufgebaut. Genauer gesagt wurde innerhalb dieser das Model-View-Presenter Muster v
Ich denke auf der äußersten Sicht handelt es sich um eine Repository Architektur (zentrales Datenhaltungs-Repository: Datenbank), mit mehreren Clients, die dann nach 3 Schichten aufgebaut sind

2018-07-15 20:06 UTC, DevWurm commented on Entwurf/entwurfsdoku.tex
> + Um die Gemeinsamkeiten zu realisieren, gibt es bei den Presenters die Klassen Appointments (zur Anzeige aller Termine) und AppointmentEntry (zur Anzeige eines Termins), die die entsprechenden Klasse
Vielleicht könnte man hier noch auf die Factory Methode eingehen

2018-07-15 20:07 UTC, DevWurm commented
Desweiteren könnte man auch auf so etwas wie ein "Komponenten Pattern" eingehen, dass ich bei uns etabliert hat. Parametrisierbare, Self-Contained Komponenten, die sich einfach wiederverwenden und einhängen lassen

2018-07-15 20:19 UTC, revilovs commented on Entwurf/entwurfsdoku.tex
> +Der Grobentwurf (dargestellt in Abbildung \ref{fig:Paketdiagramm_Grobentwurf}) wurde nach der 3-Schichtenarchitektur aufgebaut. Genauer gesagt wurde innerhalb dieser das Model-View-Presenter Muster v
Eigentlich ist es ja nur ein Client mit mehreren Views... Ich würde schon sagen dass es vordergründig 3-Schichten ist

2018-07-15 21:06 UTC, revilovs commented on Entwurf/entwurfsdoku.tex
> +Der Grobentwurf (dargestellt in Abbildung \ref{fig:Paketdiagramm_Grobentwurf}) wurde nach der 3-Schichtenarchitektur aufgebaut. Genauer gesagt wurde innerhalb dieser das Model-View-Presenter Muster v
Hast recht, ich hatte Repository mit Depot verwechselt und dachte daher Repo passt nicht

2018-07-15 21:25 UTC, DevWurm requested changes

2018-07-15 21:25 UTC, DevWurm commented on Entwurf/entwurfsdoku.tex
> +Der Grobentwurf (dargestellt in Abbildung \ref{fig:Paketdiagramm_Grobentwurf}) vereint mehrere Architekturmuster. Zum einen kann die Struktur als Repository-Architektur angesehen werden, da es versch
Das Repository aus System-Architektur-Sicht kann nicht in einem Paket sein, da es durch die Datenbank selbst umgesetzt wird. Das Repository Paket stellt nur das logische Interface im Client zum Repository dar

2018-07-15 21:25 UTC, DevWurm commented on Entwurf/entwurfsdoku.tex
> +Betrachtet man eine einzelne Ansicht, so kann diese wiederum als 3-Schichtenarchitektur gesehen werden, in der das Repository der Datenhaltungsschicht entspricht, die Models der Logikschicht und View
Das sind zwei Detaillevel: Repository Architektur auf System Ebene und im Client dann 3 Schichten

2018-07-15 21:25 UTC, DevWurm commented on Entwurf/entwurfsdoku.tex
> + Gerade an der Aufteilung in mehrere Views in der Adminansicht erkennt man sehr gut das Kompositum-Entwurfsmuster: Statt einen einzigen View mit Presenter zu bauen, wurden einzelne, selbstständige pa
Hier kann man noch auf die Kapselung der Komponenten eingehen: Die Komponenten die wir wiederverwenden, laden ihre view selbstständig und können so ohne Wissen über die Komponente von außen wiederverwendet werden. Im Gegensatz dazu haben wir "unselbsttändige-views" Bei dem der Benutzer das FXML laden und den Controller evntl. nachher noch konfigurieren  muss

2018-07-15 21:25 UTC, DevWurm commented on Entwurf/entwurfsdoku.tex
> + Um in Admin- und Studentenansicht die verschiedenen AppointmentEntry verwenden zu können, und trotzdem zur Anzeige nur die eine Methode der generalisierten Appointments-Klasse zu verwenden, wurde da
Factory-Method kombiniert mit Inheritance

2018-07-15 21:37 UTC, revilovs commented on Entwurf/entwurfsdoku.tex
> + Um in Admin- und Studentenansicht die verschiedenen AppointmentEntry verwenden zu können, und trotzdem zur Anzeige nur die eine Methode der generalisierten Appointments-Klasse zu verwenden, wurde da
Factory Method ist doch immer mit Inheritance, oder?

2018-07-15 22:01 UTC, denisk176 submitted a review, later dismissed
Ist soweit echt gut. 
Evtl. könnte man noch etwas deutlicher machen, dass bei MVP jede Schicht nur die Daten der unmittelbar darunterliegenden Schicht weiter  gibt. Aber das halte ich hier für optional.

2018-07-16 11:20 UTC, DevWurm approved these changes

2018-07-16 11:20 UTC, merged