Datenbank
htw-exam-planner/exam-planner-documentation pull request #5
Opened 2018-05-26 21:38 UTC by Dukihung

2018-05-29 16:17 UTC, revilovs requested changes
-Buchung muss Beziehungen zu Termin haben
-Reservierung muss einen FK auf Termin haben
-Die Kardinaliäten der Beziehungen stimmen nicht

2018-06-04 11:37 UTC, revilovs requested changes
-Die Kardinalitäten stimmen nicht, manche Beziehungen können ja (0...1) sein und müssen nicht 1 sein.
-Wieso hat Termin einen FK auf Datum?
-Bei Reservierung fehlt immer noch der FK auf Termin
-Bei Buchung fehlen die Datentypen
-Es gibt 2 Entities (siehst du rechts bei StarUML), die angelegt wurden, dann gelöscht, aber nur aus dem Diagramm gelöscht und nicht ganz. Bitte ganz löschen

2018-06-04 12:59 UTC, revilovs requested changes
- Bei Beziehungen zur Gruppe sind auch optionale Beziehungen (0...1)
- Termin hat keine Gruppe
- Reservierung muss FK auf Termin haben

2018-06-04 13:06 UTC, revilovs commented
Ach ja, und etwas deskriptivere Commit messages wären nicht schlecht

2018-06-04 17:03 UTC, revilovs requested changes
- Beziehungen zwischen Gruppe und Buchung/Reservierung sind falschrum (1 Buchung hat 1 Gruppe, 1 Gruppe kann 0 oder 1 Buchungen haben)
- Bei Reservierung.Gruppe fehlt referenceTo

2018-06-04 17:47 UTC, revilovs requested changes
Leider noch nicht der letzte, aber fast 😉 
- Reservierung.Gruppe muss Gruppe refernzieren, nicht Termin
- Rechts unten (wo auch PK und FK und so ist) gibt's ne Checkbox Nullable, die bestimmt ob ein Wert NULL sein darf. Überleg mal, welche Spalten NULL sein dürfen und setze das entsprechend
- Da ist außerdem eine Checkbox "Unique", mit der wir z.B. sicherstellen können, dass eine Gruppe nur 1 Buchung / Reservierung hat.
- Der SQL File sollte auch die Endung ```.sql``` haben. Du kannst ihn mit ```git mv DatenBank Datenbank.sql``` so umbenennen, dass git es mitkriegt

2018-06-04 18:11 UTC, revilovs requested changes
Fast fertig 👍, nur noch Kleinigkeiten

2018-06-04 18:11 UTC, revilovs commented on Entwurf/Datenbank.sql
> +    UNIQUE (`GruppenNummer`)
PK ist sowieso unique, das braucht man nicht extra angeben

2018-06-04 18:11 UTC, revilovs commented on Entwurf/Datenbank.sql
> +    UNIQUE (`Gruppe`, `Termin`)
Hmmm, der SQL Generator fasst die zu einem UNIQUE zusammen, das ist ja eigentlich nicht, was wir wollen. Ich denke, dann müssen wir das unique wieder rauslassen und außerhalb von StarUML selber implementieren

2018-06-04 18:11 UTC, revilovs commented on Entwurf/Datenbank.sql
> +    `Endzeit` TIME,
Darf nicht NULL sein, das ist ja das Terminzeitfenster, nicht das Buchungszeitfenster

2018-06-04 18:11 UTC, revilovs commented on Entwurf/Datenbank.sql
> +    `Raum` CHAR(15) NOT NULL,
Raum darf NULL sein

2018-06-04 19:48 UTC, revilovs requested changes
Die Änderungen sind gut, aber du solltest sie im StarUML machen, und dann das SQL neu exportieren, nicht im SQL selber rumschreiben

2018-06-06 12:37 UTC, revilovs requested changes
Sieht gut aus, @DevWurm bemerkte nur gestern richtigerweise, dass das sinnvollerweise auf Englisch sein sollte

2018-06-11 17:48 UTC, revilovs requested changes
Die Änderungen sollten bitte im StarUML gemacht werden, und dann kannst du das SQL einfach neu generieren, statt im SQL rumzuschreiben.
Ansonsten super 👍 
// von Duc Hung Nguyen
Da wurde im StarUML gemacht aber ich hab es vergessen zu speichern nachdem ich exportiert habe!

2018-06-11 18:09 UTC, revilovs requested changes
Bitte nach jeder Änderung im StarUML das SQL neu exportieren. Außerdem muss das unique bei `Reservation.Appointment` weg und es sollte `Appointment` nicht `Appointments` heißen

2018-06-11 18:23 UTC, revilovs submitted a review, later dismissed
👍

2018-06-18 10:23 UTC, DevWurm requested changes
- Warum ist bei Booking das Date der PK und bei Reservation die Group? Das ist doch inkonsistent
- Ich denke der State des Dates sollte nicht als String sondern als Referenz auf eine extra Entity abgebildet werden.
- Irgendwie ist es komisch, dass Reservierung und Buchung so von einander getrennt sind. Sie haben gemeinsame Eigenschaften und auch die Constraints überschneiden sich (es darf pro Gruppe nur eine Buchung oder Reservierung geben). Vielleicht lohnt es sich das zu generalisieren

2018-06-18 13:58 UTC, revilovs submitted a review, later dismissed

2018-06-20 07:56 UTC, revilovs requested changes
Bitte die Änderungen, die Montag besprochen wurden, realisieren. Wie immer im StarUML machen, dann SQL neu exportieren und vor dem Commit mit `git status` checken, dass alles gespeichert ist

2018-06-20 07:56 UTC, revilovs commented on Entwurf/Datenbank.sql
> +CREATE TABLE State (
Wie am Montag besprochen, soll es diese Tabelle doch nicht geben...

2018-06-20 07:56 UTC, revilovs commented on Entwurf/Datenbank.sql
> +    State INTEGER NOT NULL,
Wie am Montag besprochen, braucht das nur ein Boolean sein, der angibt ob der Termin aktiviert/ deaktiviert ist (Name wäre dann auch nicht mehr State)

2018-06-20 12:02 UTC, revilovs requested changes

2018-06-20 12:02 UTC, revilovs commented on Entwurf/Datenbank.sql
> +    Appointment BOOLEAN NOT NULL,
Also unter dem Namen kann man sich absolut nichts vorstellen. Eher sowas wie `Active` oder `Activated` oder so. Außerdem muss der FK weg (im Diagramm)

2018-06-20 12:14 UTC, revilovs submitted a review, later dismissed

2018-07-02 15:27 UTC, DevWurm submitted a review, later dismissed

2018-07-02 17:24 UTC, revilovs commented
Mir ist aufgefallen, dass Group ein reserviertes Wort ist in SQL. Das heißt, die Tabelle Group sollte noch irgendwie umbenannt werden...

2018-07-03 07:12 UTC, revilovs submitted a review, later dismissed
👍

2018-07-03 07:15 UTC, revilovs approved these changes

2018-07-03 07:15 UTC, merged