Documentation
htw-exam-planner/exam-planner-documentation pull request #6
Opened 2018-05-27 13:54 UTC by fbkr

Hier die Doku unserer Treffen. 
Feedback wäre Top.

2018-05-28 13:21 UTC, revilovs requested changes
Vielen Dank! Noch ein paar kleine Änderungen, dann passt das

2018-05-28 13:21 UTC, revilovs commented on Erstes Gruppentreffen 2304.md
> +Den 02.05. für das erste Meilensteintreffen ausgemacht.
Haben wir das nicht beim Erstgespräch ausgemacht?

2018-05-28 13:21 UTC, revilovs commented on Erstes Meilensteintreffen 0205.md
> +Ergebnis war
Hier müsste dann das Ergebnis hin...

2018-05-28 13:21 UTC, revilovs commented on Erstgespräch 2304.md
> +**Problem**: der Prozess bis zum festen Termin ist zeitaufwendig, da viel kommuniziert werden muss und Zeiträume durch die Prüfungsphase beschränkt sind.
Hier sollten die genauen Formulierungen hin, auf die wir uns geeinigt haben, siehe Mitschrift von @denisk176 . Evtl. auch was zum Vorgehen, wie wir zu den Formulierungen gekommen sind (Zettel usw.)

2018-05-28 13:21 UTC, revilovs commented on Workshop Anforderungsanalyse 0905.md
> +# Workshop Anforderungsanalyse 09.05. #
Workshop kann man das kaum nennen, war eigentlich nur ein 5-10minütiges Gespräch

2018-05-28 13:21 UTC, revilovs commented on Workshop Anforderungsanalyse 0905.md
> +Zeit:12:40 - 13.40
Ich schätze eher so 12:40-12:50

2018-05-28 13:21 UTC, revilovs commented on Workshop Anforderungsanalyse 0905.md
> +- Oliver von Seydlitz
+Denis und Hung

2018-05-28 13:21 UTC, revilovs commented on Workshop Anforderungsanalyse 0905.md
> +
Außerdem hat hier Frau Hauptmann angeboten, das Ganze als Desktop-Anwendung statt Web-Anwendung zu implementieren. Wofür wir uns dann ja entschieden haben...

2018-05-28 13:21 UTC, revilovs commented on Zweites Meilensteintreffen 1605.md
> +# 1. Hinhalte #
Ich nehme an, das sollen "Inhalte" sein

2018-05-28 13:21 UTC, revilovs commented on Zweites Meilensteintreffen 1605.md
> +Bei dem Anwendungsfall-Diagramm soll das "Include" entfernt und zwischen Gruppe löschen und Gruppe anzeigen gesetzt werden.
Sollte bei allen AWF entfernt werden, nicht nur bei Gruppen...

2018-05-29 22:30 UTC, DevWurm requested changes
Schließe mich @revilovs an

2018-05-31 10:01 UTC, denisk176 submitted a review, later dismissed
Schließe mich @DevWurm  und  @revilovs  an.

2018-06-05 11:24 UTC, DevWurm requested changes

2018-06-05 11:24 UTC, DevWurm commented on Erstgespräch 2304.md
> +# Erstgespräch 23.04. #
Das ist der Anforderungsworkshop

2018-06-05 11:24 UTC, DevWurm commented on Erstes Gruppentreffen 2304.md
> +Gruppenbesprechnung des Themas und Nachbearbeitung des Erstgesprächs.
Nachbearbeitung des Anforderungsworkshops

2018-06-05 11:24 UTC, DevWurm commented on Erstes Meilensteintreffen 0205.md
> +Konkretisierung der Termine bzw Zeiträume die in dem Projekt vorhanden sein sollen.
Der Satz ist unverständlich

2018-06-18 13:03 UTC, DevWurm requested changes
Bitte arbeite an der semantischen Struktur der Dokumente. Überschriften und Unterüberschriften, sinnvolle Gruppierung und Benennung der Notizen (Ähnlich wie bei Zweites Meilensteintreffen 1605.md)

2018-06-18 13:03 UTC, DevWurm commented on Anforderungsworkshop 2304.md
> +Inhalt des Gesprächs war die Anforderungsanalyse mit dem Auftraggeber um die Rahmenbedingungen des Projektes zu erörtern.
... um die Ziele und Rahmenbedingungen des Projektes festzustellen

2018-06-18 13:03 UTC, DevWurm commented on Anforderungsworkshop 2304.md
> +Aktuell wird eine Excel-Tabelle für die Organisation genutzt. Diese liegt nur dem Auftraggeber vor. In dieser Tabelle sind die möglichen Zeiten für einen Termin festgehalten. Der Raum, in dem dieser
Hier muss noch ne Überschrift hin

2018-06-18 13:03 UTC, DevWurm commented on Anforderungsworkshop 2304.md
> +# Anforderungsworkshop 23.04. #
Die schließenden # sind nicht notwendig

2018-06-18 13:03 UTC, DevWurm commented on Anforderungsworkshop 2304.md
> +Aktuell wird eine Excel-Tabelle für die Organisation genutzt. Diese liegt nur dem Auftraggeber vor. In dieser Tabelle sind die möglichen Zeiten für einen Termin festgehalten. Der Raum, in dem dieser
Ich denke hier sollte schon das fachliche Wording verwendet werden (also Prüfer statt Auftraggeber) und es sollte kurz erklärt werden worum es geht (Organisation von Prüfungsterminen zwischen Prüfer und Studenten)

2018-06-20 07:28 UTC, revilovs commented on Erstgespräch 2304.md
> +**Problem**: der Prozess bis zum festen Termin ist zeitaufwendig, da viel kommuniziert werden muss und Zeiträume durch die Prüfungsphase beschränkt sind.
Was ich hier meinte: Wir hatten uns in dem Treffen ja auf ganz konkrete Formulierungen für Problem und Ziel geeinigt. Da das erste Treffen ja noch @denisk176 mitgeschrieben hast und nicht du, frag ihn bitte was diese genauen Formulierungen waren

2018-06-22 13:29 UTC, revilovs requested changes
Vielen Dank, nur noch ein paar Kleinigkeiten zu tun

2018-06-22 13:29 UTC, revilovs commented on Anforderungsworkshop 2304.md
> +Aktuell wird eine Excel-Tabelle für die Organisation genutzt. Diese liegt nur dem Auftraggeber vor. In dieser Tabelle sind die möglichen Zeiten für einen Termin festgehalten. Der Raum, in dem dieser
Hier macht es eher Sinn, vom Prüfer statt vom Auftraggeber zu reden (fachlich)

2018-06-22 13:29 UTC, revilovs commented on Anforderungsworkshop 2304.md
> +der Prozess bis zum festen Termin ist zeitaufwendig, da viel kommuniziert werden muss und Zeiträume durch die Prüfungsphase beschränkt sind.
Hier bitte Denis nach der exakten Formulierung, auf die wir uns am 23.4. geeinigt hatten, fragen

2018-06-22 13:29 UTC, revilovs commented on Anforderungsworkshop 2304.md
> +Das Ziel ist eine auf den Universitätsserver hinterlegte Website (PHP). Diese Website dient als Organisationshilfe für Professoren und Studenten um Termine für Präsentationen zu vereinbaren.
Hier bitte Denis nach der exakten Formulierung, auf die wir uns am 23.4. geeinigt hatten, fragen

2018-06-22 13:29 UTC, revilovs commented on Anforderungsworkshop 2304.md
> +Prüfender, Prüfling(Gruppe).
Heißen im Pflichtenheft Administrator und Student, Prüfender und Prüfling könnte man in Klammern setzen

2018-06-22 13:29 UTC, revilovs commented on Anforderungsworkshop 2304.md
> +Ein "Kalender" auf dem 15 Tage innerhalb der Prüfungsphase einsehbar sind. Die Tage sind mit Datum markiert und unterteilt in Doppelstunden gleich dem Stundenplan der HTW. Auf dieser Oberfläche könne
Hier müsste erklärt werden, was *gebucht b.* bzw. *gebucht n.b.* ist. Ich bin mir nicht sicher, ob es in diesem Gespräch diese 5 Termine gab oder ob der 5. erst im Treffen mit Herrn Zirkelbach aufgetaucht ist

2018-06-22 13:29 UTC, revilovs commented on kurzgespraech 0905.md
> +Team-intern wurde mittles einer Umfrage ausgemacht das Projekt als Desktop-Anwendung zu realisieren.
ausgemacht, das Projekt (da muss ein Komma rein)

2018-07-12 17:01 UTC, revilovs requested changes
Noch mal ein paar Kleinigkeiten, ansonsten sieht's super aus.

2018-07-12 17:01 UTC, revilovs commented on Anforderungsworkshop 2304.md
> +•	Ein gleichzeitiges Buchen darf nicht möglich sein um Konflikte zu vermeiden.
Hier bitte Markdown-Syntax verwenden (Naja, am Ende wird's ja eh LaTeX...)

2018-07-12 17:01 UTC, revilovs commented on Anforderungsworkshop 2304.md
> +Aktuell wird eine Excel-Tabelle für die Organisation genutzt. Diese liegt nur dem Auftraggeber vor. In dieser Tabelle sind die möglichen Zeiten für einen Termin festgehalten. Der Raum, in dem dieser
Hier bitte fachliche statt technische Formulierung, also "Prüfer" statt "Auftraggeber"

2018-07-12 17:01 UTC, revilovs commented on Erstes Meilensteintreffen 0205.md
> +Die Funktion der Aktivierung und Deaktivierung der Tage mit in das Projekt aufzunehmen.
Ist glaub ich schwer zu verstehen, wenn man nicht bei dem Treffen dabei war. Eher sowas wie 
> Die gesperrten Termine werden über den Zustand "deaktiviert" abgebildet. Es ist immer ein Termin als Ganzes (d.h. ein Tag) aktiviert oder deaktiviert.

2018-07-12 20:29 UTC, revilovs commented
Da war noch ein zweites Vorkommen von "Auftraggeber", das hab ich einfach schnell ersetzt

2018-07-12 20:29 UTC, revilovs submitted a review, later dismissed

2018-07-13 07:29 UTC, DevWurm approved these changes

2018-07-13 07:31 UTC, revilovs approved these changes

2018-07-13 07:31 UTC, merged