Hier nochmal der neue Grobentwurf
htw-exam-planner/exam-planner-documentation pull request #7
Opened 2018-06-01 10:22 UTC by denisk176

Hier ist, wie vorhin besprochen der neue Grobentwurf als Paketdiagramm

2018-06-02 11:51 UTC, revilovs requested changes
Also wie gesagt ist hier auf GitHub nicht LFS-getrackt.

- Wenn die Views und Controllers Unterpakete sind, muss das über die Containment-Beziehung dargestellt werden
- Die Bausteine rechts sollten alle sinnvoll benannt sein
- Da wir bestimmt mehrere Views, Controllers und Models haben, sollten die auch plurale Namen haben
- Es fehlt die Datenhaltungsschicht
- Das Model aus MVC hat meines Wissens nichts mit dem "Model"-Baustein des Paketdiagramms zu tun, sollte also ein normales Paket sein

2018-06-02 11:52 UTC, revilovs commented
Und es wäre sinnvoll, den PR von mindestens einer anderen Person, z.B. @DevWurm reviewen zu lassen

2018-06-03 09:25 UTC, denisk176 commented
Hatte eigentlich @DevWurm angeklickt, aber anscheinend hatte er das nicht übernommen.  Habe das geändert

2018-06-04 13:13 UTC, revilovs requested changes
- LFS geht nach wie vor nicht, erinner uns morgen mal bitte dran, dass wir das checken
- Da stimmt was mit den Beziehungen nicht. Jetzt hast du Controllers conatins Model und View Contains Model, aber es müsste ja Student contains Controllers und so sein
- Models sollte auch in Mehrzahl sein

2018-06-06 12:50 UTC, revilovs commented
Krieg bitte mal dein LFS in Ordnung. Ich kann deine neusten commits nicht pullen, weil Entwurf.mdj LFS-getrackt sein sollte aber nicht ist

2018-06-06 12:51 UTC, revilovs commented
Bzw. wenn man ins mdj reinguckt sieht man sogar dass da git versucht hat was zu mergen, deswegen lässt sich der File auch in StarUML nicht mehr öffnen

2018-06-09 12:30 UTC, revilovs requested changes
- Das Diagramm sieht gut aus 👍 , aber rechts im Model Explorer stimmt die Semantik nicht ganz
- Im Model Explorer gibt es derzeit nur je 1 Paket Views und Controllers, die mehrfachen im Diagramm sind Instanzen derselben Pakete
- Das müssen verschiedene Pakete sein (sieht auf dem Diagramm danach genau so aus, nur im Explorer rechts anders)

2018-06-09 15:39 UTC, revilovs requested changes
- Sehr gut, das Diagramm ist nach wie vor gut, noch eine Kleine Änderung im Explorer rechts bitte:
- Das Paket "Models" ist derzeit unter Admin.Controllers eingeordnet, es sollte auf dem gleichen Level sein wie die anderen Top-Level-Pakete. Das sollte über drag-and-drop realisierbar sein

2018-06-09 15:55 UTC, revilovs approved these changes

2018-06-11 14:16 UTC, DevWurm approved these changes
👍

2018-06-13 16:32 UTC, merged