Feinentwurf eingefügt
htw-exam-planner/exam-planner-documentation pull request #8
Opened 2018-06-13 17:19 UTC by denisk176

Hallo Leute,

hier ist die erste Version meines Feinentwurfes. Ich bin mir ziemlich sicher, ihr werdet noch Änderungen haben. 
Teilt mir diese einfach mit. Alternativ machen wir das KD dann am Freitag (15.06) fertig.

2018-06-14 09:55 UTC, revilovs requested changes
Student, Start und Admin sind Pakete, nicht Klassen. Die Klassen müssen in die Pakete des Grobentwurfes eingeordnet werden. Die Beziehungen zwischen den Klassen fehlen

2018-06-15 11:38 UTC, revilovs requested changes
- Die Syntax der Membervariablen stimmt nicht, sie muss `name: type` sein, nicht andersrum (siehe Meldungen von StarUMLs Validierung)
- Bei Funktionen `funcname(param1: param1type): returnType`
- Beziehungen zwischen Views und Dazugeörigen Controllern (1:1-Assoziation)
- Beziehung zwischen Controllers/Views und Models ist Assoziation, nicht Aggregation (Derzeitig würde es heißen: Das Model besteht aus Controller usw.). Hier ist auch auf die Kardnialität zu achten
- Bei Models und DB fehlen noch die Membervariablen
- Bitte alle Klassen rechts im Explorer in ihre Pakete einordnen

2018-06-15 12:11 UTC, denisk176 commented
@revilovs 
> Bei Funktionen funcname(param1: param1type): returnType
Was meinst du damit genau ? Also wo würdest du noch was an den Funktionen ändern ?

2018-06-15 12:17 UTC, revilovs commented
Damit meine ich, dass das der Syntax der Funktionen im KD ist. Wenn der return type angegeben wird, dann also so, die Typen der Argumente nach dem `:` usw.

2018-06-15 12:23 UTC, denisk176 commented
@revilovs 
Das wurde doch eingehalten. Also ich sehe(noch ohne, dass ich was an den Funtionsnamen geändert habe) keine Verletzung der Syntax. 

Beispiel: `getAllAppointments(): List<Appointment>`
Hier wird keine Variable benötigt. Und am Ende werden alle Appointments in einer Liste ausgegeben.

2018-06-15 12:24 UTC, revilovs requested changes
- Einordnung mancher Klassen ins falsche Paket
- Bitte alle Validierungsergebnisse von StarUML beachten (erscheinen nach Speichern wenn man unten rechts aufs Warndreieck klickt) und Probleme beheben
- Beziehungen Controller - Model fehlen
- Beziehung Model-DB ist keine Aggreagation (DB besteht nicht aus Modellen)
- Bitte Kardinalitäten an alle Beziehungen (im Editor rechts unten das Feld "multiplicity"
- Pfeile, die in beide Richtungen gehen, bitte auseinander ziehen, dass man sieht, dass es 2 sind

2018-06-15 12:32 UTC, revilovs commented
Es ist z. B. bei `Groupmodel.generateGroups(int count)` nicht korrekt, es muss `generateGroups(count: int)` sein

2018-06-15 15:29 UTC, revilovs requested changes
- Bitte Pfeile, die in 2 Richtungen gehen, so platzieren, dass man erkennt, dass es 2 sind
- An die anderen Beziehungen (jeweils an beiden Enden) bitte die Kardinalitäten
- Da ein Model beliebig viele Views haben kann ist es vllt. sinnvoll, ein Interface View mit Methode update zu haben, von dem alle Views erben. Die Models haben dann einfach eine List<View>. @DevWurm was meinst du dazu?

2018-06-16 07:46 UTC, DevWurm commented
- Ich stimme @revilovs zu: Ein Interface für die Views wäre sehr sinnvoll, gut gesehen!
- Ich bin mir nicht sicher ob das so sein muss, aber manchmal ist bei einer Assoziation ein member für das referenzierte Objekt vorhanden (`GroupSelectionView`) und manchmal nicht (`GroupSelectionController`)
- Ich verstehe die Aufteilung nicht: Warum gibt es Model und Types? Ein Model repräsentiert die Daten eines Business Objekts und das wird aktuell durch Types abgebildet. Das was jetzt in den Models ist ist eigentlich die Business Logik, die kann entweder mit ins Model (siehe Laravel) oder in einen Extra "Service" (siehe Spring Boot)
- Die Pfeile sind aktuell so extrem unübersichtlich dass es mir schwer fällt den Inhalt zu verstehen

2018-06-16 07:47 UTC, DevWurm requested changes
- Ich stimme @revilovs zu: Ein Interface für die Views wäre sehr sinnvoll, gut gesehen!
- Ich bin mir nicht sicher ob das so sein muss, aber manchmal ist bei einer Assoziation ein member für das referenzierte Objekt vorhanden (`GroupSelectionView`) und manchmal nicht (`GroupSelectionController`)
- Ich verstehe die Aufteilung nicht: Warum gibt es Model und Types? Ein Model repräsentiert die Daten eines Business Objekts und das wird aktuell durch Types abgebildet. Das was jetzt in den Models ist ist eigentlich die Business Logik, die kann entweder mit ins Model (siehe Laravel) oder in einen Extra "Service" (siehe Spring Boot)
- Die Pfeile sind aktuell so extrem unübersichtlich dass es mir schwer fällt den Inhalt zu verstehen

2018-06-16 09:28 UTC, denisk176 commented
Ich habe versucht, die Beziehungen jetzt besser darzustellen. Weiterhin habe ich die Kardinalitäten ergänzt.

Die Pfeile in zwei Richtungen kann ich nicht als zwei Pfeile darstellen. Das macht StarUML bei mir nicht. Der merged die immer zusammen.

Wollt ihr wirklich da noch ein Interface beim Model reinbringen, dass dann Generalisierungsbeziehungen zu den Views hat ? Das wird doch noch viel unübersichtlicher

2018-06-16 09:40 UTC, revilovs commented
@DevWurm die Idee hinter den Types war: Die Types modellieren einen Termin, das Model alle Termine. Hast aber recht, dass es nicht Sinn macht, dass jetzt die Logik an der falschen Stelle ist. Das sollten wir umbauen. @DevWurm könntest du da vllt. mal am Diagramm rumbasteln? Ich denke das geht wahrscheinlich schneller als wenn @denisk176 oder ich das versuchen.
@denisk176 die Pfeile kann man trennen, indem man zusätzliche Ecken einfügt.

2018-06-16 09:41 UTC, revilovs commented
Wäre es sinnvoll, statt Model-View-Controller eher Model-View-Presenter zu nehmen? Dann gibt's weniger Beziehungen

2018-06-16 20:14 UTC, denisk176 commented
Ich habe die Pfeile jetzt getrennt, wie gewünscht. 

Ich würde bei MVC bleiben und nicht MVP nehmen. 

Wie gesagt: Wenn wir da noch ein Interface einbauen, dann wird das KD noch viel unübersichtlicher. Ich würde es daher weg lassen.

2018-06-28 14:56 UTC, revilovs requested changes
Da sind ja jetzt unsere Änderungen vom Freitag nicht mehr drin (Aufteilen in mehrere Diagramme)?? Und außerdem noch drei wichtige Buchstaben: LFS (die Bilder)

2018-06-29 07:25 UTC, revilovs requested changes
- Sticky Notes über View-Controller-Beziehung entfernen
- Mit Sticky Note erklären, was `<<FXML>>` bedeutet
- Alle Member von Views entfernen
- Größe und Positionierung von Paketen und Klassen verschönern
- In den Models die `views: List<View>` entfernen

2018-07-06 08:00 UTC, revilovs submitted a review, later dismissed

2018-07-09 07:36 UTC, DevWurm submitted a review, later dismissed

2018-07-09 08:05 UTC, revilovs approved these changes

2018-07-09 08:06 UTC, merged